"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import type { MethodCopy } from "@/lib/manufacturing";
import type { Locale } from "@/lib/i18n/locales";
import type { Dictionary } from "@/lib/i18n/dictionary";
import { pagePath } from "@/lib/i18n/routes";
export function Comparison({ locale, t, methods }: { locale: Locale; t: Dictionary; methods: Record<string, MethodCopy> }) {
  const [left, setLeft] = useState("foam"), [right, setRight] = useState("printing");
  useEffect(() => { const params = new URLSearchParams(window.location.search); const l = params.get("left"), r = params.get("right"); if (l && methods[l]) setLeft(l); if (r && methods[r]) setRight(r); if (l && r && l === r) setRight(l === "printing" ? "foam" : "printing"); }, [methods]);
  function select(side: "left" | "right", value: string) { if (!methods[value] || value === (side === "left" ? right : left)) return; side === "left" ? setLeft(value) : setRight(value); const params = new URLSearchParams({ left: side === "left" ? value : left, right: side === "right" ? value : right }); window.history.replaceState(null, "", pagePath(locale, { kind: "compare" }) + "?" + params); }
  const fields = ["cost", "detail", "mechanical", "weight", "environment", "volume", "finish"] as const;
  return <><div className="mt-8 grid gap-5 sm:grid-cols-2">{(["left", "right"] as const).map((side, index) => <label key={side} className="min-w-0 text-sm font-semibold">{index === 0 ? t.method1 : t.method2}<select className="field mt-2" value={side === "left" ? left : right} onChange={e => select(side, e.target.value)}>{Object.entries(methods).map(([id, copy]) => <option key={id} value={id} disabled={id === (side === "left" ? right : left)}>{copy.title}</option>)}</select></label>)}</div><p className="mt-5 text-sm leading-7 text-ink/65">{t.compare_note}</p><p role="status" className="sr-only">{methods[left].title} / {methods[right].title}</p><table className="method-comparison mt-8 w-full table-fixed border-collapse text-start"><caption className="sr-only">{t.compare_title}</caption><thead><tr>{[left, right].map(id => <th scope="col" key={id} className="border border-ink/15 bg-white p-3 text-start align-top md:p-5"><span className="block font-display text-xl md:text-2xl">{methods[id].title}</span><span className="mt-3 block text-sm font-normal text-bronze">{methods[id].costLabel}</span></th>)}</tr></thead>{fields.map(field => <tbody key={field}><tr><th scope="rowgroup" colSpan={2} className="border border-ink/15 bg-smoke/30 p-3 text-start text-sm">{t[`method_${field}`]}</th></tr><tr>{[left, right].map(id => <td key={id} className="border border-ink/15 p-3 align-top text-sm leading-6 md:p-5 md:text-base md:leading-7">{methods[id][field]}</td>)}</tr></tbody>)}</table><div className="mt-6 grid gap-3 sm:grid-cols-2">{[left, right].map(id => <Link className="text-link" key={id} href={pagePath(locale, { kind: "method", id })}>{methods[id].title} <span aria-hidden="true">↗</span></Link>)}</div><div className="mt-10 flex flex-wrap items-center gap-5"><Link className="button-primary" href={pagePath(locale, { kind: "contact" }) + `?method=${left}&alternative=${right}#brief`}>{t.quote_both}</Link><Link className="text-link" href={pagePath(locale, { kind: "compare" }) + `?left=${left}&right=${right}`}>{t.share_comparison}</Link></div></>;
}
