import Link from "next/link";
import { pagePath, type Page } from "@/lib/i18n/routes";
import type { Locale } from "@/lib/i18n/locales";
import { FooterLanguages } from "./footer-languages";
import type { Dictionary } from "@/lib/i18n/dictionary";
import { contactEmail } from "@/lib/contact-details";
export function LocaleFooter({ locale, t }: { locale: Locale; t: Dictionary }) {
  const kinds: Page["kind"][] = ["home", "works", "services", "compare", "about", "workshop", "contact", "selection", "planning", "industries", "concepts", "privacy"];
  return <><footer className="border-t border-ink/15 px-5 pb-24 pt-12 md:px-8"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-3"><div><p className="font-display text-3xl" dir="ltr">ARDIÇ</p><p className="mt-4 max-w-sm text-sm leading-7 text-ink/70">{t.footer_note}</p></div><nav aria-label={t.menu} className="grid grid-cols-2 gap-x-4 gap-y-1 text-sm">{kinds.map(kind => <Link className="min-h-11 py-2" key={kind} href={pagePath(locale, { kind })}>{t[`nav_${kind}` as keyof Dictionary]}</Link>)}</nav><address className="not-italic text-sm leading-7"><p className="font-semibold">{t.production_location}</p><p dir="ltr" className="mt-3">Karadeniz Caddesi No:131, Ferhatpaşa<br />Ataşehir, İstanbul, Türkiye</p><a className="mt-2 block break-all" dir="ltr" href={`mailto:${contactEmail}`}>{contactEmail}</a><a className="block" dir="ltr" href="tel:+905436268969">+90 543 626 89 69</a></address></div><nav aria-label={t.language} className="mx-auto mt-8 flex max-w-7xl flex-wrap gap-x-6 gap-y-2 border-t border-ink/15 pt-5 text-sm"><FooterLanguages locale={locale} /></nav></footer><a className="floating-contact" href={`https://wa.me/905436268969?text=${encodeURIComponent(t.whatsapp_message)}`} aria-label={`WhatsApp · ${t.direct_contact}`}><svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5a9 9 0 0 1-13.2 8L3 21l1.5-4.8A9 9 0 1 1 21 11.5Z" /><path d="M8 7.5c.5 4 4.5 8 8.5 8l1-2.2-3-1.3-1.1 1.2a9 9 0 0 1-3.6-3.6L11 8.5l-1.3-3Z" /></svg><span>WhatsApp</span></a></>;
}
