import Image from "next/image";
import Link from "next/link";
import { dictionary, type Dictionary } from "@/lib/i18n/dictionary";
import { localizedContent } from "@/lib/i18n/content";
import { methodCopy, methodIds } from "@/lib/i18n/methods";
import { countryOptions } from "@/lib/i18n/countries";
import { pagePath, type Page } from "@/lib/i18n/routes";
import type { Locale } from "@/lib/i18n/locales";
import { getProject, projects } from "@/lib/projects";
import { portfolioCategories, getPortfolioImageSrc, conceptCollections } from "@/lib/content";
import { industries } from "@/lib/industries";
import { showcase } from "@/lib/site-showcase";
import { contactEmail } from "@/lib/contact-details";
import { countryPages } from "@/lib/i18n/country-pages";
import { ProcessVisual } from "./process-visual";
import { Comparison } from "./compare";
import { SelectButton, SelectionList } from "./selection";
import { MultilingualEnquiry } from "./enquiry-form";
import { ProjectGallery } from "./project-gallery";
import { HomeShowcase, CompactMethods } from "./home-showcase";
import { InternationalSummary, ProjectDeliveryGuide } from "./project-delivery";
import { MethodEvidence } from "./method-evidence";

type Props = { locale: Locale; t: Dictionary };
export function Intro({ title, text, eyebrow }: { title: string; text: string; eyebrow?: string }) { return <div className="max-w-4xl">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1 className="mt-3 font-display text-4xl leading-tight md:text-6xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-ink/75">{text}</p></div>; }
function CTA({ locale, t }: Props) { return <section className="mt-14 border-t border-ink/15 pt-9"><h2 className="font-display text-3xl md:text-4xl">{t.cta_title}</h2><p className="mt-4 max-w-2xl leading-8 text-ink/70">{t.cta_intro}</p><Link className="button-primary mt-6" href={pagePath(locale, { kind: "contact" }) + "#brief"}>{t.nav_contact} <span aria-hidden="true">↗</span></Link></section>; }
function Steps({ t }: Pick<Props, "t">) { return <ol className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[t.step_design, t.step_production, t.step_finish, t.step_delivery].map((step, i) => <li className="border-t border-ink/15 pt-5" key={step}><span className="text-sm text-bronze" aria-hidden="true">0{i + 1}</span><h3 className="mt-2 text-lg font-semibold leading-7">{step}</h3></li>)}</ol>; }
function Scope({ locale, t, full = false }: Props & { full?: boolean }) { return <section id="project-delivery" className="mt-14 border-t border-ink/15 pt-9"><p className="eyebrow">{t.scope_eyebrow}</p><h2 className="mt-3 max-w-3xl font-display text-3xl md:text-4xl">{t.scope_title}</h2><p className="mt-4 max-w-3xl leading-8 text-ink/70">{t.scope_intro}</p><ul className="mt-6 grid gap-3 text-sm font-semibold sm:grid-cols-2 lg:grid-cols-4">{[t.scope_fitted, t.scope_free, t.scope_facade, t.scope_custom].map(item => <li className="border-s-2 border-bronze ps-3" key={item}>{item}</li>)}</ul>{full ? <><p className="mt-7 max-w-4xl leading-8 text-ink/70">{t.scope_examples}</p><Steps t={t} /><p className="mt-8 max-w-4xl text-sm leading-7 text-ink/65">{t.scope_note}</p></> : <Link className="text-link mt-6 inline-block" href={pagePath(locale, { kind: "workshop" }) + "#project-delivery"}>{t.scope_eyebrow} <span aria-hidden="true">↗</span></Link>}</section>; }
function MethodGrid({ locale, t }: Props) { return <div className="mt-8 grid gap-x-6 gap-y-8 sm:grid-cols-2 lg:grid-cols-3">{methodIds.map(id => { const copy = methodCopy(locale, id); return <article key={id} className="min-w-0"><Link href={pagePath(locale, { kind: "method", id })} className="group block"><ProcessVisual id={id} title={copy.title} illustration={t.method_visual} /><h3 className="mt-4 font-display text-2xl leading-tight group-hover:text-bronze">{copy.title} <span className="text-bronze" aria-hidden="true">↗</span></h3></Link><p className="mt-2 text-sm text-bronze">{copy.costLabel}</p></article>; })}</div>; }
function WorkCards({ locale, t, ids = projects.map(p => p.id), select = false }: Props & { ids?: string[]; select?: boolean }) { const content = localizedContent(locale); return <div className="mt-8 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{ids.map(id => { const project = getProject(id)!; const copy = content.projects[id]; return <article key={id} className="min-w-0"><Link href={pagePath(locale, { kind: "project", id })}><div className="relative aspect-[4/3] overflow-hidden bg-smoke/30"><Image src={project.image} alt={copy.title} fill sizes="(min-width: 1024px) 30vw, (min-width: 640px) 46vw, 100vw" className="object-cover" /></div><h3 className="mt-4 font-display text-2xl leading-tight">{copy.title} <span aria-hidden="true">↗</span></h3></Link>{select && <><p className="my-4 text-sm leading-7 text-ink/70">{copy.description}</p><SelectButton id={id} t={t} /></>}</article>; })}</div>; }
function ArchiveCards({ locale, t }: Props) { const content = localizedContent(locale); return <section className="mt-14 border-t border-ink/15 pt-9"><h2 className="font-display text-3xl">{t.archive}</h2><div className="mt-7 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{portfolioCategories.filter(c => c.published !== false).map(c => <Link key={c.slug} href={pagePath(locale, { kind: "archive", id: c.slug })}><div className="relative aspect-[16/10] overflow-hidden bg-smoke/30"><Image src={c.coverImage || getPortfolioImageSrc(c.images[0])} alt={content.archives[c.slug].title} fill sizes="(min-width:1024px) 30vw, 100vw" className="object-cover" /></div><h3 className="mt-3 text-lg font-semibold">{content.archives[c.slug].title} <span aria-hidden="true">↗</span></h3></Link>)}</div></section>; }
function ContactAside({ locale, t }: Props) { return <aside className="min-w-0 space-y-9"><section><h2 className="font-display text-2xl">{t.direct_contact}</h2><a className="mt-4 block break-all underline" dir="ltr" href={`mailto:${contactEmail}`}>{contactEmail}</a><a className="mt-4 block" dir="ltr" href="tel:+905436268969">+90 543 626 89 69</a><a className="mt-4 inline-block text-link" href={`https://wa.me/905436268969?text=${encodeURIComponent(t.whatsapp_message)}`}>WhatsApp ↗</a></section><section><h2 className="font-display text-2xl">{t.next_step}</h2><p className="mt-4 text-sm leading-7 text-ink/70">{t.next_step_intro}</p><Link className="text-link mt-4 inline-block" href={pagePath(locale, { kind: "services" })}>{t.explore_methods}</Link></section><section><h2 className="font-display text-2xl">{t.production_location}</h2><p className="mt-4 text-sm leading-7" dir="ltr">Karadeniz Caddesi No:131, Ferhatpaşa<br />Ataşehir, İstanbul, Türkiye</p><a className="text-link mt-4 inline-block" href="https://www.google.com/maps?q=Karadeniz%20Caddesi%20No%3A131%2C%20Ferhatpa%C5%9Fa%2C%20Ata%C5%9Fehir%2C%20Istanbul%2C%20Turkey">{t.map} ↗</a></section></aside>; }
export function LocalizedPage({ locale, page }: { locale: Locale; page: Page }) {
  const t = dictionary(locale), content = localizedContent(locale);
  const names = Object.fromEntries(Object.entries(content.projects).map(([id, copy]) => [id, copy.title]));
  const methods = Object.fromEntries(methodIds.map(id => [id, methodCopy(locale, id)]));
  const methodsNames = Object.fromEntries(Object.entries(methods).map(([id, copy]) => [id, copy.title]));
  const props = { locale, t };
  let body: React.ReactNode;
  switch (page.kind) {
    case "country": { const copy = countryPages.find(p => p.locale === locale && p.country === page.id)!; body = <><Intro title={copy.title} text={copy.description} eyebrow={t.production_location} /><div className="mt-8 max-w-4xl space-y-5 leading-8">{copy.paragraphs.map(text => <p key={text}>{text}</p>)}</div><CTA {...props} /></>; break; }
    case "home": body = <><HomeShowcase {...props} /><CompactMethods {...props} /><InternationalSummary {...props} /><section className="mt-12"><p className="eyebrow">{t.works_eyebrow}</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><h2 className="font-display text-3xl md:text-4xl">{t.works_title}</h2><Link className="text-link" href={pagePath(locale, { kind: "works" })}>{t.all_projects} ↗</Link></div><WorkCards {...props} ids={["modular-artificial-rock-concert-environment", "farmasi-boss-trip", "classical-decorative-columns"]} /></section><Scope {...props} /><CTA {...props} /></>; break;
    case "services": body = <><Intro title={t.methods_title} text={t.methods_intro} eyebrow={t.methods_eyebrow} /><Link className="text-link mt-6 inline-block" href={pagePath(locale, { kind: "compare" })}>{t.compare_cta} ↗</Link><MethodGrid {...props} /><p className="mt-7 text-sm leading-7 text-ink/65">{t.cost_note}</p><CTA {...props} /></>; break;
    case "method": { const copy = methods[page.id!]; body = <><Intro title={copy.title} text={copy.intro} eyebrow={t.methods_eyebrow} /><div className="mt-7 flex flex-wrap gap-3"><Link className="button-primary" href={pagePath(locale, { kind: "contact" }) + `?method=${page.id}#brief`}>{t.nav_contact}</Link><Link className="button-secondary" href={pagePath(locale, { kind: "compare" }) + `?left=${page.id}&right=${page.id === "glass" ? "carbon" : "glass"}`}>{t.nav_compare}</Link></div><div className="mt-9 max-w-4xl"><ProcessVisual id={page.id!} title={copy.title} illustration={t.method_visual} detail /></div><div className="mt-10 grid gap-8 md:grid-cols-2">{(["cost", "detail", "mechanical", "weight", "environment", "volume", "finish"] as const).map(key => <section key={key} className="border-t border-ink/15 pt-5"><h2 className="font-display text-2xl">{t[`method_${key}`]}</h2>{key === "cost" && <p className="mt-2 text-sm font-semibold text-bronze">{copy.costLabel}</p>}<p className="mt-3 leading-8 text-ink/70">{copy[key]}</p></section>)}</div>{copy.processes && <section className="mt-12 border-t border-ink/15 pt-8"><h2 className="font-display text-3xl">{t.method_processes}</h2><div className="mt-6 grid gap-7 lg:grid-cols-3">{copy.processes.map(process => <article key={process.title} className="border border-ink/15 bg-white p-5"><h3 className="font-display text-2xl">{process.title}</h3><p className="mt-4 leading-7">{process.how}</p><p className="mt-3 text-sm leading-7 text-ink/70">{process.fit}</p><p className="mt-3 text-sm leading-7 text-ink/65">{process.tradeoff}</p></article>)}</div></section>}<div className="mt-10 grid gap-8 md:grid-cols-2">{(["steps", "uses", "drivers", "limits"] as const).map(key => <section key={key} className="border-t border-ink/15 pt-5"><h2 className="font-display text-2xl">{t[`method_${key}`]}</h2><ul className="mt-4 list-disc space-y-3 ps-5 leading-7 text-ink/70">{copy[key].map(value => <li key={value}>{value}</li>)}</ul></section>)}</div>{copy.faqs.length > 0 && <section className="mt-10"><h2 className="font-display text-3xl">{t.method_faq}</h2>{copy.faqs.map(faq => <details className="mt-4 border-y border-ink/15 py-4" key={faq.question}><summary className="cursor-pointer font-semibold">{faq.question}</summary><p className="mt-4 leading-8 text-ink/70">{faq.answer}</p></details>)}</section>}{page.id === "wood" && <Scope {...props} full />}<MethodEvidence {...props} id={page.id!} /><CTA {...props} /></>; break; }
    case "compare": body = <><Intro title={t.compare_title} text={t.methods_intro} /><Comparison {...props} methods={methods} /></>; break;
    case "works": body = <><Intro title={t.nav_works} text={t.works_intro} eyebrow={t.works_eyebrow} /><WorkCards {...props} select /><ArchiveCards {...props} /><CTA {...props} /></>; break;
    case "project": { const project = getProject(page.id!)!, copy = content.projects[page.id!]; body = <><Link className="text-link mb-6 inline-block" href={pagePath(locale, { kind: "works" })}>{t.all_projects}</Link><Intro title={copy.title} text={copy.description} eyebrow={t.project_details} /><div className="mt-6 flex flex-wrap items-center gap-3"><Link className="button-primary" href={pagePath(locale, { kind: "contact" }) + `?selected=${project.id}#brief`}>{t.nav_contact}</Link><SelectButton id={project.id} t={t} /></div>{copy.facts && <section className="mt-8" aria-labelledby="project-facts"><h2 id="project-facts" className="font-display text-2xl">{t.project_facts}</h2><dl className="mt-4 grid gap-5 sm:grid-cols-3">{copy.facts.map(fact => <div key={fact.label} className="border-t border-ink/15 pt-4"><dt className="text-xs font-semibold text-bronze">{fact.label}</dt><dd className="mt-2 text-sm leading-7">{fact.value}</dd></div>)}</dl></section>}{project.gallery ? <ProjectGallery project={project} copy={copy} /> : <div className="relative mt-8 aspect-[4/3] max-w-5xl overflow-hidden bg-smoke/30 md:aspect-[16/10]"><Image src={project.image} alt={copy.title} fill priority sizes="90vw" className="object-contain" /></div>}{project.id === showcase[0].id && <div className="mt-8 grid gap-5 sm:grid-cols-2">{[showcase[0].image, ...["side-view", "full-stage", "performance-detail-01", "performance-detail-02"].map(name => "/works/modular-artificial-rock-concert-environment/concert-rock-environment-" + name + ".jpeg")].map((src, i) => <div className="relative aspect-[4/3] bg-smoke/30" key={src}><Image src={src} alt={`${copy.title} · ${t.photo} ${i + 2}`} fill sizes="(min-width:640px) 45vw, 100vw" className="object-contain" /></div>)}</div>}{copy.details && <div className="mt-8 max-w-3xl space-y-3 leading-8 text-ink/70">{copy.details.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div>}<section className="mt-10 max-w-3xl border-t border-ink/15 pt-8"><h2 className="font-display text-3xl">{t.similar_brief}</h2><p className="mt-4 leading-8 text-ink/70">{t.brief_checklist}</p><Link className="button-primary mt-6" href={pagePath(locale, { kind: "contact" }) + `?selected=${project.id}#brief`}>{t.nav_contact}</Link></section></>; break; }
    case "archive": { const archive = portfolioCategories.find(c => c.slug === page.id)!; const copy = content.archives[page.id!]; body = <><Intro title={copy.title} text={t.archive_intro} eyebrow={t.archive} /><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{archive.images.map((img, index) => { const src = getPortfolioImageSrc(img); return <a href={src} target="_blank" rel="noopener" key={`${src}-${index}`} aria-label={`${copy.title} · ${t.photo} ${index + 1}`}><figure><div className="relative aspect-[4/3] overflow-hidden bg-smoke/30"><Image src={src} alt={`${copy.title} · ${t.photo} ${index + 1}`} fill sizes="(min-width:1024px) 30vw, (min-width:640px) 46vw, 100vw" className="object-contain" /></div><figcaption className="mt-2 text-xs text-ink/60">{t.photo} {index + 1}</figcaption></figure></a>; })}</div><CTA {...props} /></>; break; }
    case "workshop": body = <><Intro title={t.workshop_title} text={t.workshop_intro} eyebrow={t.production_location} /><div className="mt-9 grid gap-6 md:grid-cols-3">{["foam", "tooling", "cnc"].map(id => <ProcessVisual key={id} id={id} title={methods[id].title} illustration={t.method_visual} />)}</div><Scope {...props} full /><section className="mt-10"><h2 className="font-display text-3xl">{t.international_title}</h2><p className="mt-4 max-w-4xl leading-8 text-ink/70">{t.international_intro}</p></section><CTA {...props} /></>; break;
    case "about": body = <><div className="grid items-center gap-8 lg:grid-cols-2"><Intro title={t.about_title} text={t.about_intro} eyebrow={t.nav_about} /><ProcessVisual id="foam" title={t.workshop_title} illustration={t.method_visual} /></div><section className="mt-12 border-t border-ink/15 pt-8"><h2 className="font-display text-3xl">{t.team}</h2><div className="mt-7 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{content.team.map(person => <article className="flex items-center gap-4 border-t border-ink/15 pt-5" key={person.name}>{person.photo ? <Image src={person.photo} alt={person.name} width={64} height={64} className="h-16 w-16 object-cover" /> : <span className="flex h-16 w-16 shrink-0 items-center justify-center bg-smoke/40 font-display text-2xl text-bronze" aria-hidden="true">{person.initials}</span>}<div><h3 className="font-display text-2xl"><bdi>{person.name}</bdi></h3><p className="mt-2 text-sm leading-6 text-bronze">{person.role}</p></div></article>)}</div></section><Scope {...props} /><CTA {...props} /></>; break;
    case "contact": body = <><Intro title={t.contact_title} text={t.contact_intro} /><div className="mt-9 grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_300px]"><MultilingualEnquiry {...props} methods={methodsNames} countries={countryOptions(locale)} projectNames={names} /><ContactAside {...props} /></div></>; break;
    case "selection": body = <><Intro title={t.nav_selection} text={t.selection_intro} /><SelectionList {...props} names={names} /></>; break;
    case "privacy": body = <><Intro title={t.privacy_title} text={t.privacy_body} /><div className="mt-8 max-w-3xl space-y-6 leading-8 text-ink/70"><p>{t.privacy_services}</p><p>{t.privacy_selection}</p><p>{t.nda_note}</p><a className="text-link" href={`mailto:${contactEmail}`} dir="ltr">{contactEmail}</a></div></>; break;
    case "concepts": body = <><Intro title={t.nav_concepts} text={t.concepts_intro} /><div className="mt-9 space-y-12">{conceptCollections.map(concept => <section className="border-t border-ink/15 pt-7" key={concept.number}><p className="eyebrow"><bdi>{concept.number}</bdi> · {t.nav_concepts}</p><h2 className="mt-3 font-display text-3xl">{content.concepts[concept.number].title}</h2><p className="mt-4 max-w-3xl leading-8 text-ink/70">{content.concepts[concept.number].description}</p>{concept.image && <div className="relative mt-6 aspect-[16/10] max-w-5xl bg-smoke/30"><Image src={concept.image} alt={content.concepts[concept.number].title} fill sizes="90vw" className="object-contain" /></div>}{concept.galleryImages && <div className="mt-5 grid grid-cols-2 gap-4 md:grid-cols-4">{concept.galleryImages.map((img, index) => <a href={img.src} key={img.src} target="_blank" rel="noopener"><div className="relative aspect-square bg-smoke/30"><Image src={img.src} alt={`${content.concepts[concept.number].title} · ${t.photo} ${index + 2}`} fill sizes="25vw" className="object-cover" /></div></a>)}</div>}</section>)}</div><CTA {...props} /></>; break;
    case "planning": body = <><Intro title={t.nav_planning} text={t.planning_intro} eyebrow={t.guide_eyebrow} /><ProjectDeliveryGuide {...props} /><Scope {...props} /><CTA {...props} /></>; break;
    case "industries": body = <><Intro title={t.nav_industries} text={t.applications_intro} /><div className="mt-8 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{industries.map(industry => <article key={industry.slug}><Link href={pagePath(locale, { kind: "industry", id: industry.slug })}><div className="relative aspect-[4/3] bg-smoke/30"><Image src={industry.image} alt={content.industries[industry.slug].title} fill sizes="(min-width:1024px) 30vw, 100vw" className="object-cover" /></div><h2 className="mt-4 font-display text-2xl">{content.industries[industry.slug].title} ↗</h2></Link><p className="mt-3 text-sm leading-7 text-ink/70">{content.industries[industry.slug].description}</p></article>)}</div></>; break;
    case "industry": { const copy = content.industries[page.id!]; body = <><Intro title={copy.title} text={copy.description} eyebrow={t.nav_industries} /><p className="mt-6 max-w-3xl text-sm leading-7 text-ink/65">{t.applications_intro}</p><WorkCards {...props} ids={projects.filter(p => p.industries.includes(page.id!)).map(p => p.id)} /><section className="mt-10"><h2 className="font-display text-3xl">{t.similar_brief}</h2><p className="mt-4 leading-8 text-ink/70">{t.brief_checklist}</p><Link className="button-primary mt-6" href={pagePath(locale, { kind: "contact" }) + `?industry=${page.id}#brief`}>{t.nav_contact}</Link></section></>; break; }
  }
  return <main id="main-content" className={`page-shell ${page.kind === "home" ? "home-shell" : ""}`}>{body}</main>;
}
